---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: dns-ubuntu-devel
    image: ubuntu:devel
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-devel
