---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  vars:
    _nslookup_package:
      Alpine: bind-tools
      Archlinux: dnsutils
      Debian: dnsutils
      RedHat: &redhat_nslookup_package bind-utils
      Rocky: *redhat_nslookup_package

    nslookup_package: "{{ _nslookup_package[ansible_os_family] }}"

  tasks:
    - name: Install nslookup
      ansible.builtin.package:
        name: "{{ nslookup_package }}"
        state: present
      notify:
        - Uninstall nslookup

    - name: Test resolving www.example.com
      ansible.builtin.command:
        cmd: nslookup www.example.com 127.0.0.1
      changed_when: false

  handlers:
    - name: Uninstall nslookup
      ansible.builtin.package:
        name: "{{ nslookup_package }}"
        state: absent
